<?php
return array (
  4 => 
  array (
    'id' => '4',
    'content' => 'say hello',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '0',
    'template' => '',
    'paytype' => '0',
    'relation' => '',
    'voteid' => '0',
    'allow_comment' => '1',
    'copyfrom' => '|0',
    'catid' => '12',
    'typeid' => '0',
    'title' => '你好中国',
    'style' => '',
    'thumb' => '/uploadfile/2017/1023/20171023044045443.jpg',
    'keywords' => '中国 你好',
    'description' => 'say hello',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=12&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1508747253',
    'updatetime' => '1508752969',
  ),
  3 => 
  array (
    'id' => '3',
    'content' => '新西兰CARDRONA滑雪场已持续两年赞助南山自由滑雪公开赛的国内本土高手赴新西兰滑雪，今年2月，曾率领新西兰自由式滑雪国家队征战索契冬奥会的Peter Legnavsky先生亲赴南山开展青少年自由式滑雪公开课，Peter同时也是CARDRONA滑雪场公园部经理，当北半球的雪季结束，夏天到来，他和滑雪场的国际教练们，在新西兰等着小伙伴们！新西兰CARDRONA滑雪场已持续两年赞助南山自由滑雪公开赛的国内本土高手赴新西兰滑雪，今年2月，曾率领新西兰自由式滑雪国家队征战索契冬奥会的Peter Legnavsky先生亲赴南山开展青少年自由式滑雪公开课，Peter同时也是CARDRONA滑雪场公园部经理，当北半球的雪季结束，夏天到来，他和滑雪场的国际教练们，在新西兰等着小伙伴们！',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '0',
    'template' => '',
    'paytype' => '0',
    'relation' => '',
    'voteid' => '0',
    'allow_comment' => '1',
    'copyfrom' => '|0',
    'catid' => '12',
    'typeid' => '0',
    'title' => '烟台勃朗滑雪，相当于免费喽！！只要您转发...',
    'style' => '',
    'thumb' => '/uploadfile/2017/1023/20171023044045443.jpg',
    'keywords' => '勃朗 烟台',
    'description' => '新西兰CARDRONA滑雪场已持续两年赞助南山自由滑雪公开赛的国内本土高手赴新西兰滑雪，今年2月，曾率领新西兰自由式滑雪国家队征战索契冬奥   ',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=12&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1508747210',
    'updatetime' => '1508752959',
  ),
  2 => 
  array (
    'id' => '2',
    'content' => '祝福恩教授强调，党的十八届六中全会以全面从严治党为主题，是按&ldquo;四个全面&rdquo;战略布局规划设计的收官之作，是以习近平同志为核心的党中央立足现实着眼未来的顶层设计，充分体现了&ldquo;习核心&rdquo;治党治国的科学理念，有效解决了全面从严治党的世界级难题，为实现新长征宏伟目标提供了领导核心保证。全会报告共有6000多字，思想深遂，概括准确，内容丰富，博大精深，细读起来有十大亮点： 1.一个核心：即明确提出了&ldquo;以习近平同志为核心的党中央&rdquo;。这个表述体现了全党和全国人民的根本利益，为打胜改革攻坚战并完成全面建成小康社会任务，实现新长征宏伟目标提供根本保证。 2.两个&ldquo;关键&rdquo;：即&ldquo;办好中国的事情，关键在党，关键在党要管党，从严治党。&rdquo;&ldquo;两个关键&rdquo;论述了六中全会以全面从严治党为主题的份量和深远价值。 3.三个文件：即审议通过三个文件：《准则》《条例》和《关于召开党的第十九次全国代表大会的决议》<br />
<img alt="" src="/uploadfile/2017/1023/20171023042640987.jpg" style="width: 550px; height: 366px;" /><br />
',
    'readpoint' => '0',
    'groupids_view' => '',
    'paginationtype' => '0',
    'maxcharperpage' => '0',
    'template' => '',
    'paytype' => '0',
    'relation' => '',
    'voteid' => '0',
    'allow_comment' => '1',
    'copyfrom' => '|0',
    'catid' => '12',
    'typeid' => '0',
    'title' => '2月1日起，学生免费滑雪开始了',
    'style' => '',
    'thumb' => '/uploadfile/2017/1023/20171023042640987.jpg',
    'keywords' => '学生',
    'description' => '祝福恩教授强调，党的十八届六中全会以全面从严治党为主题，是按四个全面战略布局规划设计的收官之作，是以习近平同志为核心的党中央立足现   ',
    'posids' => '0',
    'url' => '/index.php?m=content&c=index&a=show&catid=12&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1508747163',
    'updatetime' => '1508747203',
  ),
);
?>